export const CART_ACTIONS = new Set([
  'CART_ADD', 'CART_REMOVE', 'CART_SET_QTY', 'CART_CLEAR', 'SET_CART',
  'WISHLIST_TOGGLE', 'SET_WISHLIST', 'CART_MOVE_TO_WISHLIST', 'CART_MOVE_ALL_TO_WISHLIST',
])
